name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 5.0.x

    - name: Make publish.sh executable
      run:  chmod +x publish.sh
    - name: Build and Publish
      run: ./publish.sh
      
    - name: Archive build results
      uses: actions/upload-artifact@v4
      with:
        name: dist-without-markdown
        path: |
          publish
          !publish/issuer.dll.md
